
import React from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, Download, Copy, Share2 } from 'lucide-react';
import { toast } from "@/hooks/use-toast";

interface SummaryDisplayProps {
  summary: string;
  fileName: string;
}

export const SummaryDisplay: React.FC<SummaryDisplayProps> = ({ summary, fileName }) => {
  const handleDownloadPDF = () => {
    // Simulate PDF generation and download
    const blob = new Blob([summary], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName.split('.')[0]}_summary.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Summary downloaded!",
      description: "Your document summary has been saved successfully.",
    });
  };

  const handleCopySummary = () => {
    navigator.clipboard.writeText(summary);
    toast({
      title: "Copied to clipboard!",
      description: "Summary has been copied to your clipboard.",
    });
  };

  return (
    <Card className="mt-8">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center">
            <FileText className="h-5 w-5 mr-2" />
            Document Summary
          </CardTitle>
          <div className="flex space-x-2">
            <Button variant="outline" size="sm" onClick={handleCopySummary}>
              <Copy className="h-4 w-4 mr-1" />
              Copy
            </Button>
            <Button size="sm" onClick={handleDownloadPDF}>
              <Download className="h-4 w-4 mr-1" />
              Download PDF
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="bg-gray-50 rounded-lg p-6 border-l-4 border-indigo-500">
          <div className="mb-4">
            <span className="text-sm font-medium text-gray-600">
              Summary for: {fileName}
            </span>
          </div>
          <div className="prose prose-sm max-w-none">
            <pre className="whitespace-pre-wrap font-sans text-gray-800 leading-relaxed">
              {summary}
            </pre>
          </div>
        </div>
        
        <div className="mt-4 flex items-center justify-between text-sm text-gray-500">
          <span>Generated by Learn Smart AI</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </CardContent>
    </Card>
  );
};
